### ISSUE TITLE
Instructions on https://github.com/nektos/act#installation-as-github-cli-extension seem to be incomplete or not working (yet?)

### ISSUE THREAD

**Issue by okurz** [nektos/gh-act#2]
## Observation
Following https://github.com/nektos/act#installation-as-github-cli-extension I called

```
gh extension install nektos/gh-act
```

which cloned the repo but doesn't seem to provide an executable:

```
$ gh act
failed to run extension: fork/exec ~/.local/share/gh/extensions/gh-act/gh-act: no such file or directory
```

I might be doing it wrong though :)

**Comment by cplee** [comment]
@okurz - I'm unable to reproduce. I'm on a mac and I tried the following:

* Ensure I had latest GitHub CLI (2.22.1)
* Install gh-act: `gh extension install nektos/gh-act`
* Run act `gh act`
* Worked as expected

What operating system are you on? What version of GitHub CLI? What does your `~/.local/share/gh/extensions` directory look like?

**Comment by okurz** [comment]
> @okurz - I'm unable to reproduce. I'm on a mac and I tried the following:
> 
>     * Ensure I had latest GitHub CLI (2.22.1)
> 
>     * Install gh-act: `gh extension install nektos/gh-act`
> 
>     * Run act `gh act`
> 
>     * Worked as expected
> 
> 
> What operating system are you on?

openSUSE Leap 15.4

> What version of GitHub CLI?

2.0.0 which I realize now is quite old. I installed the current version 2.22.1 from https://software.opensuse.org//download.html?project=devel%3Atools%3Ascm&package=gh and `gh act` reproduces the same problem

> What does your `~/.local/share/gh/extensions` directory look like?

It only contains "gh-act".

I crosschecked in an openSUSE Tumbleweed container:

```
podman run --pull=always --rm -it registry.opensuse.org/opensuse/tumbleweed
zypper in -n gh
gh auth login
gh extension install nektos/gh-act
gh act
```

There everything works fine.

Using a clean Leap 15.4 container reproduces the original problem with version gh 2.0.0 but a Leap 15.5 (Beta) container with gh version 2.14.2 show no problem as well. With that I see that there still is an issue and it can even be reproduced but obviously a new version of gh fixes it so I need to just find a solution for my own current setup :) Thanks for your response and support.
